file_format: "1"
id: silakka54
name: Silakka54
type: shield
url: https://github.com/vandermey/silakka54-zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - encoder
siblings:
  - silakka54_left
  - silakka54_right
